export const SEARCH_FOCUS = 'search_focus'
export const SEARCH_BLUR = 'search_blur'
export const SEARCH_HOT_LIST = 'search_hot_list'
export const MOUSE_ENTER = 'mouse_enter'
export const MOUSE_LEAVE = 'mouse_leave'
export const PAGE_CHANGE = 'page_change'